# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml

environment:
  matrix:
    - platform: x64

branches:
  only:
    - master

image: Visual Studio 2015

init:
  - npm config set msvs_version 2015 # we need this to build `pty.js`

install:
  - ps: Install-Product node 6 x64
  - set CI=true
  - npm install -g npm@3.10.8
  - npm install

build: off

shallow_clone: true

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test

on_success:
  - npm run package
