# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml

environment:
  matrix:
    - platform: x64

branches:
  only:
    - master

image: Visual Studio 2015

init:
  - npm config set msvs_version 2015 # we need this to build `pty.js`

install:
  - ps: Install-Product node 8 x64
  - set CI=true
  - yarn

build: off

shallow_clone: true

test_script:
  - node --version
  - yarn --version
  - yarn run lint
  - yarn run test

on_success:
  - yarn run package

cache:
 - "%LOCALAPPDATA%\\Yarn"
